import 'package:flutter/material.dart';

const backgroundColor = Colors.white;

const STATION_NAMES = [
  'Adamstown',
  'Ardrahan',
  'Arklow',
  'Ashtown',
  'Athenry',
  'Athlone',
  'Athy',
  'Attymon',
  'Balbriggan',
  'Ballina',
  'Ballinasloe',
  'Ballybrophy',
  'Ballyhaunis',
  'Ballymote',
  'Banteer',
  'Bayside',
  'Belfast Lanyon Place',
  'Birdhill',
  'Blackrock',
  'Booterstown',
  'Boyle',
  'Bray',
  'Broombridge',
  'Cahir',
  'Carlow',
  'Carrick-on-Shannon',
  'Carrick-on-Suir',
  'Carrigaloe',
  'Carrigtwohill',
  'Castlebar',
  'Castleconnell',
  'Castleknock',
  'Castlerea',
  'Charleville',
  'Clara',
  'Claremorris',
  'Clondalkin Fonthill',
  'Clongriffin',
  'Clonmel',
  'Clonsilla',
  'Clontarf Road',
  'Cloughjordan',
  'Cobh',
  'Collooney',
  'Coolmine',
  'Cork',
  'Craughwell',
  'Dalkey',
  'Docklands',
  'Donabate',
  'Drogheda',
  'Dromod',
  'Drumcondra',
  'Dublin Connolly',
  'Dublin Heuston',
  'Dublin Pearse',
  'Dun Laoghaire',
  'Dunboyne',
  'Dundalk',
  'Edgeworthstown',
  'Enfield',
  'Ennis',
  'Enniscorthy',
  'Farranfore',
  'Fota',
  'Foxford',
  'Galway',
  'Glenageary',
  'Glounthaune',
  'Gorey',
  'Gormanston',
  'Gort',
  'Grand Canal Dock',
  'Greystones',
  'Hansfield',
  'Harmonstown',
  'Hazelhatch and Celbridge',
  'Howth',
  'Howth Junction and Donaghmede',
  'Kilbarrack',
  'Kilcock',
  'Kilcoole',
  'Kildare',
  'Kilkenny',
  'Killarney',
  'Killester',
  'Killiney',
  'Lansdowne Road',
  'Laytown',
  'Leixlip (Confey)',
  'Leixlip (Louisa Bridge)',
  'Limerick',
  'Limerick Junction',
  'Lisburn',
  'Little Island',
  'Longford',
  'Lurgan',
  'M3 Parkway',
  'Malahide',
  'Mallow',
  'Manulla Junction',
  'Maynooth',
  'Midleton',
  'Millstreet',
  'Monasterevin',
  'Muine Bheag',
  'Mullingar',
  'Navan Road Parkway',
  'Nenagh',
  'Newbridge',
  'Newry',
  'Oranmore',
  'Park West and Cherry Orchard',
  'Portadown',
  'Portarlington',
  'Portlaoise',
  'Portmarnock',
  'Raheny',
  'Rathdrum',
  'Rathmore',
  'Roscommon',
  'Roscrea',
  'Rosslare Europort',
  'Rosslare Strand',
  'Rush and Lusk',
  'Rushbrooke',
  'Sallins and Naas',
  'Salthill and Monkstown',
  'Sandycove and Glasthule',
  'Sandymount',
  'Seapoint',
  'Shankill',
  'Sixmilebridge',
  'Skerries',
  'Sligo',
  'Sutton',
  'Sydney Parade',
  'Tara Street',
  'Templemore',
  'Thomastown',
  'Thurles',
  'Tipperary',
  'Tralee',
  'Tullamore',
  'Waterford',
  'Westport',
  'Wexford',
  'Wicklow',
  'Woodlawn',
  'Daly',
  'Kent',
  'MacBride',
  'Mallin',
  'Clarke',
  'Ceannt',
  'MacDonagh',
  'Confey',
  'Louisa Bridge',
  'Colbert',
  'Bagenalstown',
  'MacDiarmada',
  'Casement',
  'Plunkett',
  'O Hanrahan'
];
